make errorbackoff customizeable for yawol-controller
stackitcloud/yawol pull request #139
Opened 2023-03-16 10:47 UTC by breuerfelix

2023-03-16 12:33 UTC, nschad reviewed
just a tiny nit. I would rename that to `errorBackoffInitialDelay` or maybe even `errorInitialBackOffDelay`, whatever sounds more correct :)

2023-03-16 12:33 UTC, nschad commented on charts/yawol-controller/values.yaml
> +  errorBackoffBaseDelay: 5ms
```suggestion
  errorBackoffInitialDelay: 5ms
```

2023-03-16 12:33 UTC, nschad commented on cmd/yawol-controller/main.go
> +	var errorBackoffBaseDelay time.Duration
```suggestion
	var errorBackoffInitialDelay time.Duration
```

2023-03-16 12:43 UTC, breuerfelix commented
@nschad the official kubernetes variable is called base delay thats why i named it like this :)

2023-03-17 07:48 UTC, dergeberl submitted a review, later dismissed

2023-03-23 15:16 UTC, dergeberl requested changes

2023-03-23 15:16 UTC, dergeberl commented on charts/yawol-controller/templates/yawol-controller.yaml
>          args:
I think we should add this to all 3 controllers not only the lb and lbm controller

2023-03-28 07:12 UTC, dergeberl submitted a review, later dismissed

2023-03-29 14:43 UTC, dergeberl submitted a review, later dismissed

2023-03-29 14:44 UTC, dergeberl approved these changes

2023-03-29 14:49 UTC, merged