allow setting external labels for log forward in yawollet
stackitcloud/yawol pull request #198
Opened 2023-07-05 14:29 UTC by breuerfelix

Expectations: "You can do YAWOL in your last sprint!"
Reality: Adding 3 lines in some Helmchart.

So here i am, making things complicated for you with some innovative json to yaml marshalling!

2023-07-05 14:35 UTC, nschad approved these changes

2023-07-05 14:38 UTC, nschad reviewed
Würde noch in der README auf der Front page ein Beispiel einfügen

2023-07-07 13:56 UTC, dergeberl requested changes

2023-07-07 13:56 UTC, dergeberl commented on README.md
> +    logging.yawol.stackit.cloud/foo: "bar"
I would add a second label to make clear that it is possible to set multible ones.

2023-07-07 14:36 UTC, dergeberl approved these changes

2023-07-18 13:09 UTC, merged