Allow configuration of the subnet the LB is placed in
stackitcloud/yawol pull request #287
Opened 2024-02-14 15:15 UTC by malt3

This is an optional parameter that can either be left uninitialized to keep the old behavior or be set as a helm value or per LB.

We at edgeless systems have a use-case for yawol where we need to loadbalancer to be in the same network but a different subnet (cidr) than the kubernetes nodes.
This is a requirement for the network encryption we are using in our clusters.
Basically, we need to enforce that any traffic in the node subnet cidr belongs to a k8s node (and can thus enforce it to be encrypted).
Loadbalancer traffic must therefore be part of a separate subnet.

2024-02-16 13:29 UTC, dergeberl commented
Thanks for your contribution 🥳 

Can you please add a test to check that `createPort` is correct if there is a subnet set and if there is no subnet set?

2024-02-16 17:06 UTC, malt3 commented
> Can you please add a test to check that `createPort` is correct if there is a subnet set and if there is no subnet set?

I added tests for the loadbalancermachine controller behavior. Please let me know if there is more testing needed!

2024-02-20 14:53 UTC, dergeberl commented
> I added tests for the loadbalancermachine controller behavior. Please let me know if there is more testing needed!

Can you please add one more test for the yawol-cloud-controller. To test that it also works that a subnet can be set via an annotation. 
Like this:
https://github.com/stackitcloud/yawol/blob/19dcae4f7bee3a8f41275e26e1f0220fcfb8885e/controllers/yawol-cloud-controller/targetcontroller/service_controller_test.go#L2187

2024-04-15 08:15 UTC, Kumm-Kai requested changes
Thanks for your contribution, just a few additional comments :)

2024-04-15 08:15 UTC, Kumm-Kai commented on controllers/yawol-controller/loadbalancermachine/loadbalancermachine_controller_test.go
> +				g.Expect(len(port.FixedIPs)).To(Equal(1))
Use `.To(HaveLen(1))` instead.

2024-04-15 08:15 UTC, Kumm-Kai commented on controllers/yawol-controller/loadbalancer/loadbalancer_controller.go
Can you please also extend the tests in `loadbalancer_controller_test.go`

2024-05-10 16:26 UTC, malt3 commented on controllers/yawol-controller/loadbalancer/loadbalancer_controller.go
I'm not sure what exactly you would like to validate here. This file also does not contain tests for the main `DefaultNetwork.NetworkID` field.

2024-05-14 07:00 UTC, Kumm-Kai commented on controllers/yawol-controller/loadbalancer/loadbalancer_controller.go
Tbh I'm also not sure what we've wanted to have covered there. Maybe to ensure that if `DefaultNetwork.SubnetID` is set that the port will use this subnet. But I think we can keep it like it is for now.

2024-05-14 11:27 UTC, Kumm-Kai approved these changes

2024-05-14 11:39 UTC, merged

2024-05-14 11:40 UTC, Kumm-Kai commented
Thanks for your contribution! ❤️