API change
stackitcloud/yawol pull request #83
Opened 2022-12-13 14:25 UTC by breuerfelix

* comments out the environment variables since it always causes a diff when using external files. (it also causes a diff if you replace them in the file aswell, so keeping the file externally at least doesn't cause a diff anymore
* sets the default classname to "test" in the example file since `run-ycc` defaults to this classname aswell
* removes snake case api json annotations
* adds migration code for api changes

2022-12-13 14:49 UTC, nschad reviewed
we should create a new api version if possible

2022-12-13 14:58 UTC, dergeberl commented
> we should create a new api version if possible

We decided to not do this until we released version v1 of yawol to not end up in `v1betaXX`

2022-12-13 15:03 UTC, dergeberl requested changes

2022-12-13 15:03 UTC, dergeberl commented on api/v1beta1/loadbalancer_types.go
> +	// Deprecated: used for migration
This will be rendered in the crd so it makes sense to reference to the new field like
```suggestion
	// Deprecated: use imageID instead
```

2022-12-13 15:39 UTC, breuerfelix commented
> we should create a new api version if possible

we wanna do that after version 1.0

2022-12-19 07:45 UTC, dergeberl approved these changes
lgtm

2022-12-22 09:45 UTC, merged